apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeflow-pipeline-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kubeflow.k8s.hydrosphere.io
    http:
      paths:
      - path: /
        backend:
          serviceName: ml-pipeline-ui 
          servicePort: 80
